using UnityEngine.Localization;

namespace VRBuilder.Core.TextToSpeech
{
    /// <summary>
    /// Interface implemented by content generated by a TTS provider.
    /// </summary>
    public interface ITextToSpeechContent
    {
        /// <summary>
        /// Text content to be fed to the TTS provider.
        /// </summary>
        string Text { get; }
        
        /// <summary>
        /// The speaker to use for the TTS provider if supported.
        /// </summary>
        string Speaker { get; }
    }
}
